projects:
  - name: DeepSpotCloud
    photo: /assets/images/deepspotcloud.png
    url: https://bigdata.cs.kookmin.ac.kr/deep-spot-cloud-demo
    description: Provides a way to execute DeepLearning tasks in a cost efficient way using GPU-based spot instances on AWS EC2.

  - name: Handling checkpointfile on Tensorflow
    photo: /assets/images/project/tensorflow.jpg
    url: #
    description: Focusing on file reduction of checkpointfile on Tensorflow